<?php

$labels = array();
$labels['label'] = 'Štítky';
$labels['label0'] = 'Důležité';
$labels['label1'] = 'Pracovní';
$labels['label2'] = 'Osobní';
$labels['label3'] = 'Udělat';
$labels['label4'] = 'Později';

$labels['tb_label_options'] = 'Štítky';
$labels['tb_label_button_label'] = 'Štítky';
$labels['tb_label_button_title'] = 'Nastavení štítků zprávy';
$labels['tb_label_label'] = 'Štítek';

$messages = array();

