<?php
/**
* Author:
* Michael Kefeder
* http://code.google.com/p/rcmail-thunderbird-labels/
*/

$labels = array();
$labels['label'] = 'Schlagwörter';
$labels['label0'] = 'Wichtig';
$labels['label1'] = 'Dienstlich';
$labels['label2'] = 'Persönlich'; // grün
$labels['label3'] = 'Zu Erledigen'; // blau
$labels['label4'] = 'Später';

$labels['tb_label_options'] = 'Labels';
$labels['tb_label_button_label'] = 'Labels';
$labels['tb_label_button_title'] = 'Nachricht Label`n';
$labels['tb_label_label'] = 'Label';

$messages = array();
