<?php
/**
* Author:
* Michael Kefeder
* http://code.google.com/p/rcmail-thunderbird-labels/
*/

$labels = [];
$labels['label'] = 'Labels';
$labels['label0'] = 'Important';
$labels['label1'] = 'Work';
$labels['label2'] = 'Personal';
$labels['label3'] = 'To do';
$labels['label4'] = 'Later';

$labels['tb_label_options'] = 'Labels';
$labels['tb_label_button_label'] = 'Labels';
$labels['tb_label_button_title'] = 'Set labels on messages';
$labels['tb_label_label'] = 'Label';

$messages = [];
