<?php
/*
 +-----------------------------------------------------------------------+
| Localization file of the Roundcube Thunderbird Labels plugin          |
| Copyright (C) 2013, JPL TSolucio, S.L. (Joe Bordes)                   |
|                                                                       |
| Licensed under the GNU General Public License version 3 or            |
| any later version.                                                    |
|                                                                       |
+-----------------------------------------------------------------------+
*/

$labels = array();
$labels['label'] = 'Etiquetas';
$labels['label0'] = 'Importante';
$labels['label1'] = 'Trabajo';
$labels['label2'] = 'Personal';
$labels['label3'] = 'Por Hacer';
$labels['label4'] = 'Más Tarde';

$messages = array();

