<?php
/**
* Author:
* Michael Kefeder
* http://code.google.com/p/rcmail-thunderbird-labels/
*/

$labels = array();
$labels['label'] = 'Tags';
$labels['label0'] = 'Important';
$labels['label1'] = 'Travail';
$labels['label2'] = 'Personnel';
$labels['label3'] = 'A faire';
$labels['label4'] = 'Plus tard';

$labels['tb_label_options'] = 'Tags';
$labels['tb_label_button_label'] = 'Tags';
$labels['tb_label_button_title'] = 'Affecter des tags aux messages';
$labels['tb_label_label'] = 'Tag';
