<?php
/**
* Author:
* Samuele Tognini <samuele@samuele.netsons.org>
* http://code.google.com/p/rcmail-thunderbird-labels/
*/

$labels = array();
$labels['label'] = 'Etichette';
$labels['label0'] = 'Importante';
$labels['label1'] = 'Lavoro';
$labels['label2'] = 'Personale';
$labels['label3'] = 'Da fare';
$labels['label4'] = 'Piu\' tardi';

$labels['tb_label_options'] = 'Etichette';
$labels['tb_label_button_label'] = 'Etichette';
$labels['tb_label_button_title'] = 'Assegna etichette al messaggio';
$labels['tb_label_label'] = "Label";

$messages = array();

