<?php
/**
* Author:
* master771
* http://code.google.com/p/rcmail-thunderbird-labels/
*/

$labels = array();
$labels['label'] = 'Etykiety';
$labels['label0'] = 'Ważne';
$labels['label1'] = 'Praca';
$labels['label2'] = 'Osobiste';
$labels['label3'] = 'Do zrobienia';
$labels['label4'] = 'Później';

$labels['tb_label_options'] = 'Etykiety';
$labels['tb_label_button_label'] = 'Etykiety';
$labels['tb_label_button_title'] = 'Ustaw etykiety dla wiadomości';
$labels['tb_label_label'] = 'Etykieta';

$messages = array();

