<?php
/**
* Author:
* Michael Kefeder
* http://code.google.com/p/rcmail-thunderbird-labels/
*/

$labels = array();
$labels['label'] = 'Etiquetas';
$labels['label0'] = 'Importante';
$labels['label1'] = 'Trabalho';
$labels['label2'] = 'Pessoal';
$labels['label3'] = 'Fazer';
$labels['label4'] = 'Depois';

$labels['tb_label_options'] = 'Etiquetas';
$labels['tb_label_button_label'] = 'Etiquetas';
$labels['tb_label_button_title'] = 'Definir etiquenas nas mensagens';
$labels['tb_label_label'] = "Etiqueta";

$messages = array();
