<?php
/**
* Author:
* Николай Николай
* http://code.google.com/p/rcmail-thunderbird-labels/
*/

$labels = array();
$labels['label'] = 'Метка';
$labels['label0'] = 'Важное';
$labels['label1'] = 'Рабочее';
$labels['label2'] = 'Личное';
$labels['label3'] = 'К исполнению';
$labels['label4'] = 'Отложено';

$labels['tb_label_options'] = 'Метки';
$labels['tb_label_button_label'] = 'Метки';
$labels['tb_label_button_title'] = 'Присвоить сообщению метку';
$labels['tb_label_label'] = "Метка";

$messages = array();
