<?php

$labels = array();
$labels['label'] = 'Štítky';
$labels['label0'] = 'Uôležité';
$labels['label1'] = 'Pracovné';
$labels['label2'] = 'Osobné';
$labels['label3'] = 'Urobiť';
$labels['label4'] = 'Neskôr';

$labels['tb_label_options'] = 'Štítky';
$labels['tb_label_button_label'] = 'Štítky';
$labels['tb_label_button_title'] = 'Nastavení štítků zprávy';
$labels['tb_label_label'] = 'Štítek';

$messages = array();
