<?php
/**
* Author:
* Mykyta Solomko
* http://code.google.com/p/rcmail-thunderbird-labels/
*/

$labels = array();
$labels['label'] = 'Мітки';
$labels['label0'] = 'Важливе';
$labels['label1'] = 'Робоче';
$labels['label2'] = 'Особисте';
$labels['label3'] = 'До виконання';
$labels['label4'] = 'Відсунуте';

$labels['tb_label_options'] = 'Мітки';
$labels['tb_label_button_label'] = 'Мітки';
$labels['tb_label_button_title'] = 'Встановити мітки на повідомленнях';
$labels['tb_label_label'] = 'Мітка';

$messages = array();

